using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using QingJie;
using Geometry = QingJie.Geometry;
class Tests {
    static int count;
    static void Check(bool condition,string name){if(!condition)throw new Exception(name);Console.WriteLine("PASS "+name);count++;}
    static T Await<T>(Task<T> task){var frame=new System.Windows.Threading.DispatcherFrame();task.ContinueWith(t=>frame.Continue=false);System.Windows.Threading.Dispatcher.PushFrame(frame);return task.GetAwaiter().GetResult();}
    static void Finish(Task task){Await(task.ContinueWith(t=>{t.GetAwaiter().GetResult();return true;}));}
    static void WritingTests(){
        var previous=SynchronizationContext.Current;SynchronizationContext.SetSynchronizationContext(new System.Windows.Threading.DispatcherSynchronizationContext());
        try{
            int calls=0;string target=null;CancellationToken token=CancellationToken.None;TaskCompletionSource<string> reply=null;
            var window=new WriteTranslationWindow((text,cancel,language)=>{calls++;target=language;token=cancel;reply=new TaskCompletionSource<string>();return reply.Task;});
            var input=(System.Windows.Controls.TextBox)LogicalTreeHelper.FindLogicalNode(window,"TranslationInput");
            var output=(System.Windows.Controls.TextBox)LogicalTreeHelper.FindLogicalNode(window,"TranslationOutput");
            var languageBox=(System.Windows.Controls.Button)LogicalTreeHelper.FindLogicalNode(window,"TranslationTarget");
            var copy=(System.Windows.Controls.Button)LogicalTreeHelper.FindLogicalNode(window,"CopyTranslation");
            var button=(System.Windows.Controls.Button)LogicalTreeHelper.FindLogicalNode(window,"TranslateInput");
            var resultArea=(System.Windows.Controls.StackPanel)LogicalTreeHelper.FindLogicalNode(window,"TranslationResultArea");
            Check(window.WindowStyle==WindowStyle.None&&window.Width==400&&window.SizeToContent==SizeToContent.Height&&resultArea.Visibility==Visibility.Collapsed&&copy.Visibility==Visibility.Collapsed,"minimal writer hides empty output and copy action without a title bar");
            Check(!button.IsEnabled&&!copy.IsEnabled&&languageBox.Content.ToString().Contains("英文"),"writing window defaults to English with no automatic request");
            input.Text="请确认交货日期，谢谢。";Check(calls==0&&button.IsEnabled,"typing alone never sends text or runs OCR");
            var work=window.TranslateNow();Check(calls==1&&target=="en"&&!copy.IsEnabled,"writing explicitly requests English and disables copying until success");reply.SetResult("Please confirm the delivery date. Thank you.");Finish(work);Check(output.Text.Contains("delivery")&&copy.IsEnabled,"writing result can be selected and copied");
            languageBox.RaiseEvent(new RoutedEventArgs(System.Windows.Controls.Button.ClickEvent));Check(output.Text==""&&!copy.IsEnabled&&calls==1,"changing target clears old translation without automatic upload");
            work=window.TranslateNow();Check(target=="zh","writing can also translate into Chinese");input.Text="新的内容";Check(token.IsCancellationRequested&&!copy.IsEnabled,"editing cancels old translation");reply.SetResult("obsolete");Finish(work);Check(output.Text=="","late response cannot overwrite changed input");
            Check(resultArea.Visibility==Visibility.Collapsed&&copy.Visibility==Visibility.Collapsed,"clearing obsolete translation also collapses unused result UI");
            work=window.TranslateNow();languageBox.RaiseEvent(new RoutedEventArgs(System.Windows.Controls.Button.ClickEvent));Check(token.IsCancellationRequested,"target switch cancels in-flight writing request");reply.SetResult("旧译文");Finish(work);Check(output.Text==""&&!copy.IsEnabled,"late response from previous language stays hidden");
            work=window.TranslateNow();AppState.Settings.TranslationProvider="google";AppState.ProviderChanged();Check(token.IsCancellationRequested,"provider switch cancels in-flight input request");reply.SetResult("previous service");Finish(work);Check(output.Text==""&&!copy.IsEnabled,"provider switch never mislabels an old translation");AppState.Settings.TranslationProvider="tencent";AppState.ProviderChanged();
            input.Text=new string('字',5001);int before=calls;Finish(window.TranslateNow());Check(calls==before&&!button.IsEnabled&&input.Text.Length==5001,"oversized input is explained without silently truncating or uploading");
            input.Text="测试";work=window.TranslateNow();reply.SetException(new InvalidOperationException("test service failure"));Finish(work);Check(output.Text==""&&!copy.IsEnabled&&button.IsEnabled,"service failure preserves input and permits retry");
            work=window.TranslateNow();window.Close();Check(token.IsCancellationRequested,"closing writing window cancels network work");reply.SetResult("late");Finish(work);Check(output.Text=="","closed writing window ignores completed request");
        }finally{SynchronizationContext.SetSynchronizationContext(previous);}
    }
    static void LanguageSelectionTests(){
        var preferences=new Preferences {OcrLanguage="kor"};var packs=new System.Collections.Generic.HashSet<string>{"kor","fra"};int saves=0,removes=0;bool failSave=false,failRemove=false;
        var selection=new OcrLanguageSelection(preferences,()=>{saves++;if(failSave)throw new IOException("synthetic save error");},id=>packs.Contains(id),id=>{removes++;if(failRemove)throw new IOException("synthetic delete error");packs.Remove(id);});
        Check(selection.SelectedId=="kor"&&selection.CurrentId=="kor"&&saves==0,"OCR selector initially matches actual saved language without saving");
        selection.Choose("fra");Check(selection.SelectedId=="fra"&&selection.CurrentId=="fra"&&saves==1,"installed OCR language switches immediately on selection");
        selection.Choose("fra");Check(saves==1,"reselecting active OCR language does not rewrite settings");
        selection.Choose("jpn");Check(selection.SelectedId=="jpn"&&selection.CurrentId=="fra"&&!selection.Ready&&saves==1,"browsing uninstalled language does not activate or download it");
        bool missing=false;try{selection.Apply();}catch(InvalidOperationException){missing=true;}Check(missing&&selection.CurrentId=="fra","missing language cannot become active");
        selection.Choose("");Check(selection.CurrentId==""&&selection.SelectedId==""&&selection.Ready&&saves==2,"built-in Chinese and English activate immediately without downloading");
        selection.Choose("kor");failSave=true;bool failed=false;try{selection.Choose("fra");}catch(IOException){failed=true;}Check(failed&&preferences.OcrLanguage=="kor"&&selection.SelectedId=="kor","save failure restores both active language and dropdown selection");failSave=false;
        selection.Choose("jpn");packs.Add("jpn");failSave=true;failed=false;try{selection.Apply();}catch(IOException){failed=true;}Check(failed&&selection.CurrentId=="kor"&&selection.SelectedId=="jpn"&&selection.Ready,"downloaded pack with failed settings save is not falsely activated");failSave=false;selection.Apply();Check(selection.CurrentId=="jpn","downloaded language can be activated by explicit retry");
        failSave=true;failed=false;try{selection.Remove();}catch(IOException){failed=true;}Check(failed&&packs.Contains("jpn")&&removes==0&&selection.CurrentId=="jpn","uninstall refuses to delete active model when fallback cannot be saved");failSave=false;
        failRemove=true;failed=false;try{selection.Remove();}catch(IOException){failed=true;}Check(failed&&packs.Contains("jpn")&&selection.CurrentId=="jpn","failed uninstall restores previous language setting");failRemove=false;
        selection.Remove();Check(!packs.Contains("jpn")&&selection.CurrentId==""&&selection.SelectedId=="","successful active-model uninstall restores default and dropdown together");
        Check(packs.Contains("kor")&&packs.Contains("fra"),"language switching and uninstall preserve other installed language packs");
        bool unknown=false;try{selection.Choose("unknown");}catch(ArgumentException){unknown=true;}Check(unknown&&selection.CurrentId==""&&selection.SelectedId=="","invalid language never changes selection or current preference");
        preferences.OcrLanguage="jpn";var missingSelection=new OcrLanguageSelection(preferences,()=>{},id=>packs.Contains(id),id=>{});Check(missingSelection.SelectedId=="jpn"&&!missingSelection.Ready,"saved but missing language pack remains visible for recovery, never shown as enabled");
        var previousPins=AppState.Pins;AppState.Pins=new PinStore(Path.Combine(Path.GetTempPath(),"Luma-Language-UI-"+Guid.NewGuid().ToString("N")));SettingsWindow window=null;
        try{
            var uiPreferences=new Preferences {OcrLanguage="kor"};int uiSaves=0;var uiSelection=new OcrLanguageSelection(uiPreferences,()=>uiSaves++,OcrLanguagePacks.Installed,id=>{});window=new SettingsWindow(uiSelection);
            var dropdown=(System.Windows.Controls.ComboBox)LogicalTreeHelper.FindLogicalNode(window,"OcrLanguages");var action=(System.Windows.Controls.Button)LogicalTreeHelper.FindLogicalNode(window,"ApplyOcrLanguage");
            Check((string)((System.Windows.Controls.ComboBoxItem)dropdown.SelectedItem).Tag=="kor"&&!action.IsEnabled&&uiSaves==0,"settings dropdown opens on active language with disabled already-enabled action");
            dropdown.SelectedItem=dropdown.Items.Cast<System.Windows.Controls.ComboBoxItem>().First(i=>(string)i.Tag=="fra");Check(uiPreferences.OcrLanguage=="fra"&&uiSaves==1&&!action.IsEnabled,"actual settings selection event immediately applies installed language");
            dropdown.SelectedIndex=0;Check(uiPreferences.OcrLanguage==""&&uiSaves==2&&!action.IsEnabled,"actual default option switches both Chinese-English setting and button state");
        }finally{if(window!=null)window.Close();AppState.Pins=previousPins;}
    }
    static void ShortcutTests(){
        var keys=new ShortcutSet();Check(keys.Error()==null&&keys.Capture.ToString()=="F1"&&keys.Pin.ToString()=="F3"&&keys.Translate.ToString()=="Ctrl+Alt+T","default shortcuts preserve screenshot and pin behaviour");
        var restored=new System.Web.Script.Serialization.JavaScriptSerializer().Deserialize<Preferences>("{\"Stroke\":3}");Check(restored.Shortcuts.Error()==null&&restored.TranslationProvider=="tencent","old settings migrate with defaults without extra downloads");
        Check(Shortcut.FromKey(System.Windows.Input.Key.K,System.Windows.Input.ModifierKeys.Control|System.Windows.Input.ModifierKeys.Shift).ToString()=="Ctrl+Shift+K"&&!Shortcut.FromKey(System.Windows.Input.Key.K,System.Windows.Input.ModifierKeys.None).Valid(),"hotkey capture accepts modifiers but not unmodified typing");
        var duplicate=keys.Copy();duplicate.Pin=duplicate.Capture.Copy();Check(duplicate.Error()!=null,"duplicate hotkeys are rejected");
        var held=new System.Collections.Generic.Dictionary<int,Shortcut>();Shortcut blocked=null;int registrations=0;
        using(var manager=new HotkeyManager((id,key)=>{registrations++;if(key.Same(blocked)||held.Values.Any(k=>k.Same(key)))return false;held[id]=key.Copy();return true;},id=>held.Remove(id))){
            Check(manager.Start(keys)==null&&held.Count==3,"hotkeys start without a keyboard hook");int captureId=held.First(k=>k.Value.Same(keys.Capture)).Key;int pinId=held.First(k=>k.Value.Same(keys.Pin)).Key;int before=registrations;
            var swapped=keys.Copy();swapped.Capture=keys.Pin.Copy();swapped.Pin=keys.Capture.Copy();Check(manager.Apply(swapped,()=>{})==null&&registrations==before&&manager.ActionFor(captureId)==1&&manager.ActionFor(pinId)==0,"swapping owned shortcuts reuses registration with no failure window");
            var candidate=keys.Copy();candidate.Capture=new Shortcut {Key=0x4B,Modifiers=3};candidate.Pin=new Shortcut {Key=0x4C,Modifiers=3};blocked=candidate.Pin;bool saved=false;
            Check(manager.Apply(candidate,()=>saved=true)!=null&&!saved&&held.Count==3&&held.Values.Any(k=>k.Same(keys.Capture))&&!held.Values.Any(k=>k.Same(candidate.Capture)),"conflict releases only tentative registrations and preserves old shortcuts");
            blocked=null;Check(manager.Apply(candidate,()=>{throw new IOException("test settings failure");})!=null&&held.Count==3&&manager.ActionFor(captureId)==1,"settings write failure rolls back new hotkeys without losing old ones");
            Check(manager.Apply(candidate,()=>saved=true)==null&&saved&&held.Values.Any(k=>k.Same(candidate.Capture))&&!held.ContainsKey(captureId)&&manager.ActionFor(captureId)==-1,"successful apply atomically commits settings and retires old shortcuts");
        }Check(held.Count==0,"exit releases only app-owned hotkeys");
    }
    static BitmapSource LegacyPrepare(BitmapSource source,double ratio){
        var bgra=new FormatConvertedBitmap(source,PixelFormats.Bgra32,null,0);int width=source.PixelWidth,height=source.PixelHeight;var pixels=new byte[width*height*4];bgra.CopyPixels(pixels,width*4,0);
        int dark=0,samples=0;for(int i=0;i<pixels.Length;i+=64){if(pixels[i]*.0722+pixels[i+1]*.7152+pixels[i+2]*.2126<100)dark++;samples++;}
        for(int i=0;i<pixels.Length;i+=4){int gray=(int)(pixels[i]*.0722+pixels[i+1]*.7152+pixels[i+2]*.2126);gray=(gray*pixels[i+3]+255*(255-pixels[i+3]))/255;if(dark>samples*.6)gray=255-gray;pixels[i]=pixels[i+1]=pixels[i+2]=(byte)gray;pixels[i+3]=255;}
        var normalized=BitmapSource.Create(width,height,96,96,PixelFormats.Bgra32,null,pixels,width*4);normalized.Freeze();var scaled=new TransformedBitmap(normalized,new ScaleTransform(ratio,ratio));scaled.Freeze();return scaled;
    }
    static bool SamePixels(BitmapSource a,BitmapSource b){if(a.PixelWidth!=b.PixelWidth||a.PixelHeight!=b.PixelHeight)return false;var bytesA=new byte[a.PixelWidth*a.PixelHeight*4];var bytesB=new byte[bytesA.Length];new FormatConvertedBitmap(a,PixelFormats.Bgra32,null,0).CopyPixels(bytesA,a.PixelWidth*4,0);new FormatConvertedBitmap(b,PixelFormats.Bgra32,null,0).CopyPixels(bytesB,b.PixelWidth*4,0);return bytesA.SequenceEqual(bytesB);}
    [STAThread] static int Main(string[] args){try{
        AppState.Settings=new Preferences();
        if(args.Length==1&&args[0]=="--offline-live"){OfflineTests.Live(Check);Console.WriteLine(count+" offline live tests passed.");return 0;}
        OcrLanguagePacks.TestFolder=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"test-languages");OcrLanguagePacks.TestSelection=Environment.GetEnvironmentVariable("QINGJIE_TEST_LANGUAGE")??"";
        if(args.Length==2&&args[0]=="--speed-probe"){
            var source=Snapshot.Load(args[1]);for(int run=0;run<3;run++){var timer=System.Diagnostics.Stopwatch.StartNew();var speedPage=Await(OcrService.Read(source));long ocr=timer.ElapsedMilliseconds;var speedRegions=ImageTranslation.Regions(speedPage);var translated=Await(Translation.TranslateImage(speedRegions.Select(r=>r.Text).ToArray(),CancellationToken.None));long network=timer.ElapsedMilliseconds-ocr;ImageTranslation.Render(source,speedRegions,translated);Console.WriteLine("run="+run+" ocr_ms="+ocr+" translate_ms="+network+" render_ms="+(timer.ElapsedMilliseconds-ocr-network)+" total_ms="+timer.ElapsedMilliseconds+" regions="+speedRegions.Count);Console.WriteLine(string.Join(" | ",translated));}return 0;
        }
        if(args.Length==2&&args[0]=="--tess-probe"){
            var source=Snapshot.Load(args[1]);var prepared=OcrService.Prepare(source,3);byte[] png;using(var memory=new MemoryStream()){var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(prepared));encoder.Save(memory);png=memory.ToArray();}
            foreach(var mode in new[]{Tesseract.PageSegMode.SparseText,Tesseract.PageSegMode.Auto})using(var engine=new Tesseract.TesseractEngine(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"tessdata"),"kor",Tesseract.EngineMode.LstmOnly)){engine.SetVariable("thresholding_method",2);engine.SetVariable("thresholding_kfactor",0.04);using(var pix=Tesseract.Pix.LoadFromMemory(png))using(var result=engine.Process(pix,mode))using(var it=result.GetIterator()){it.Begin();do{Console.WriteLine(mode+" confidence="+it.GetConfidence(Tesseract.PageIteratorLevel.TextLine)+" "+it.GetText(Tesseract.PageIteratorLevel.TextLine));}while(it.Next(Tesseract.PageIteratorLevel.TextLine));}}return 0;
        }
        if(args.Length==2&&args[0]=="--ocr-image"){Console.WriteLine("OCR languages: "+OcrService.Languages());Console.WriteLine(Await(OcrService.Read(Snapshot.Load(args[1]))).Text);return 0;}
        if(args.Length==3&&args[0]=="--translate-image"){var source=Snapshot.Load(args[1]);var recognized=Await(OcrService.Read(source));Console.WriteLine(recognized.Text);var regionsToTranslate=ImageTranslation.Regions(recognized);var translated=Translation.TranslateImage(regionsToTranslate.Select(r=>r.Text).ToArray(),CancellationToken.None).GetAwaiter().GetResult();Console.WriteLine(string.Join("\n",translated));ImageFiles.Write(ImageTranslation.Render(source,regionsToTranslate,translated),args[2]);return 0;}
        if(args.Length==1&&args[0]=="--context-probe"){Console.WriteLine(Translation.Translate("[[[0000]]]\nReady. Create. Fold.\n\n[[[0001]]]\nGimbal first, then body up. Body down, then gimbal folds.\n\n[[[0002]]]\nManually adjustable mast\n\n[[[0003]]]\nSet camera height by hand, independent of wheel lifts.",CancellationToken.None).GetAwaiter().GetResult());return 0;}
        Check(Geometry.Clamp(30,1,25)==25&&Geometry.Clamp(-2,1,25)==1,"line width clamped");
        long cacheTime=0;var textCache=new TranslationCache(40,2,1,()=>cacheTime);var cacheValue=new[]{"译文"};textCache.Put("first",cacheValue);cacheValue[0]="changed";Check(textCache.Get("first")[0]=="译文","translation cache isolates caller mutations");var cacheRead=textCache.Get("first");cacheRead[0]="changed";Check(textCache.Get("first")[0]=="译文","translation cache returns a copy");textCache.Put("second",new[]{"二"});textCache.Get("first");textCache.Put("third",new[]{"三"});Check(textCache.Get("second")==null&&textCache.Count==2,"translation cache evicts least recently used entries");textCache.Put(new string('x',50),new[]{"large"});Check(textCache.CharacterCount<=40,"translation cache refuses oversized entries");cacheTime=1000;Check(textCache.Count==0&&textCache.Get("first")==null,"translation cache expires without a resident timer");
        int translating=0,maxTranslating=0;var parallelResult=Await(Translation.TranslateImageCore(new[]{"alpha","제품 사용","omega"},CancellationToken.None,async(input,token)=>{translating++;maxTranslating=Math.Max(maxTranslating,translating);try{await Task.Delay(input.Contains("alpha")?100:10,token);return "[[[0000]]]\n"+(input.Contains("alpha")?"甲":input.Contains("omega")?"丙":"乙");}finally{translating--;}}));Check(parallelResult.SequenceEqual(new[]{"甲","乙","丙"})&&maxTranslating==2,"parallel language translation preserves order and two-request limit");
        bool invalidBlock=false;try{Await(Translation.TranslateImageCore(new[]{"alpha"},CancellationToken.None,(input,token)=>Task.FromResult("missing marker")));}catch(InvalidOperationException){invalidBlock=true;}Check(invalidBlock,"parallel malformed translation never accepted or cached");
        Check(Translation.TextCacheKey("hello","en")!=Translation.TextCacheKey("hello","zh")&&Translation.ImageCacheKey(new[]{"hello"},"en")!=Translation.ImageCacheKey(new[]{"hello"},"zh"),"both translation caches isolate target languages");
        var requestJson=new System.Web.Script.Serialization.JavaScriptSerializer().Deserialize<System.Collections.Generic.Dictionary<string,object>>(Translation.RequestJson(new[]{"请确认交货日期"},"auto","en"));
        Check(((System.Collections.Generic.Dictionary<string,object>)requestJson["target"])["lang"].ToString()=="en"&&((System.Collections.Generic.Dictionary<string,object>)requestJson["source"])["lang"].ToString()=="auto","Chinese input request uses selected English target and automatic source");
        var englishGlossary=Await(Translation.TranslateImageCore(new[]{"gimbal Fold"},CancellationToken.None,(input,token)=>Task.FromResult("[[[0000]]]\ngimbal Fold"),"en"));Check(englishGlossary[0]=="gimbal Fold","Chinese-only device glossary never rewrites English output");
        bool invalidTarget=false;try{Translation.TargetLanguage("xx");}catch(ArgumentException){invalidTarget=true;}Check(invalidTarget,"unsupported target rejected before network request");
        var screenshotTarget=Ui.TranslationTarget("zh",language=>{});Check(screenshotTarget.SelectedIndex==0,"screenshot translation still defaults to Chinese independently of writing");
        WritingTests();
        ShortcutTests();
        LanguageSelectionTests();
        OfflineTests.Run(Check);
        Check(Translation.TextCacheKey("hello","en","google")!=Translation.TextCacheKey("hello","en","tencent")&&Translation.ImageCacheKey(new[]{"hello"},"en","google")!=Translation.ImageCacheKey(new[]{"hello"},"en","tencent"),"both translation caches isolate providers");
        Check(GoogleTranslation.Parse("[[[\"Hello. \",\"你好。\",null,null],[\"Thank you.\",\"谢谢。\",null,null]],null,\"zh-CN\"]")=="Hello. Thank you.","Google response segments preserve text order");
        bool googleInvalid=false;try{GoogleTranslation.Parse("<html>blocked</html>");}catch(InvalidOperationException){googleInvalid=true;}Check(googleInvalid,"Google blocked or malformed responses never render as translation");
        string chunkSource=new string('中',698)+"[[[0001]]]\n"+new string('文',699)+"\U0001F600"+new string('字',1300);var chunks=GoogleTranslation.Chunks(chunkSource);Check(string.Concat(chunks)==chunkSource&&chunks.All(c=>c.Length<=700&&!char.IsHighSurrogate(c[c.Length-1]))&&chunks.Any(c=>c.Contains("[[[0001]]]")),"Google bounded requests preserve every character, surrogate and image marker");
        var alphaPixels=new byte[33*27*4];new Random(41).NextBytes(alphaPixels);var alphaSample=BitmapSource.Create(33,27,96,96,PixelFormats.Bgra32,null,alphaPixels,33*4);alphaSample.Freeze();
        foreach(double ratio in new[]{.5,1,2.5,3})Check(SamePixels(LegacyPrepare(alphaSample,ratio),OcrService.Prepare(alphaSample,ratio)),"compact grayscale is pixel-identical for alpha/color at scale "+ratio);
        var startupFolder=Path.Combine(Path.GetTempPath(),"QingJie-Startup-Test-"+Guid.NewGuid().ToString("N"));
        var startup=new StartupRegistration(startupFolder,typeof(Program).Assembly.Location);
        Check(!startup.Enabled,"startup is off when shortcut absent");startup.SetEnabled(true);Check(startup.Enabled,"startup enable creates own shortcut");startup.SetEnabled(true);Check(startup.Enabled,"startup enable is idempotent");startup.SetEnabled(false);Check(!startup.Enabled&&!File.Exists(startup.ShortcutPath),"startup disable removes only own shortcut");
        Check(Path.GetFileName(startup.ShortcutPath)=="Luma.lnk","new installations use Luma startup name");
        startup.SetEnabled(true);var legacyStartupPath=Path.Combine(startupFolder,"轻截.lnk");File.Move(startup.ShortcutPath,legacyStartupPath);Check(startup.Enabled&&startup.ShortcutPath==legacyStartupPath,"existing startup remains enabled after Luma rename");startup.SetEnabled(true);Check(File.Exists(legacyStartupPath)&&!File.Exists(Path.Combine(startupFolder,"Luma.lnk")),"legacy startup identity preserved for Windows disabled-startup preference");startup.SetEnabled(false);Check(!File.Exists(legacyStartupPath)&&!startup.Enabled,"disable removes legacy startup after branding upgrade");
        var otherStartup=new StartupRegistration(startupFolder,Path.Combine(startupFolder,"Other.exe"));otherStartup.SetEnabled(true);bool protectedShortcut=false;try{startup.SetEnabled(false);}catch(InvalidOperationException){protectedShortcut=true;}Check(protectedShortcut&&otherStartup.Enabled,"unrelated startup shortcut is protected");otherStartup.SetEnabled(false);Directory.Delete(startupFolder);
        var reverse=Geometry.FromPoints(new Point(80,40),new Point(20,10));Check(reverse.Width==60&&reverse.Height==30,"reverse drag selection");
        var samplePixels=new byte[]{1,0,0,255,2,0,0,255,3,0,0,255,4,0,0,255,5,0,0,255,6,0,0,255};var rotationSample=BitmapSource.Create(3,2,96,96,PixelFormats.Bgra32,null,samplePixels,12);rotationSample.Freeze();
        var rotated=PinTransforms.Apply(rotationSample,1,false,false);var rotatedBytes=new byte[24];rotated.CopyPixels(rotatedBytes,8,0);Check(rotated.PixelWidth==2&&rotated.PixelHeight==3&&new[]{rotatedBytes[0],rotatedBytes[4],rotatedBytes[8],rotatedBytes[12],rotatedBytes[16],rotatedBytes[20]}.SequenceEqual(new byte[]{4,1,5,2,6,3}),"clockwise rotation is pixel exact and swaps dimensions");
        var horizontal=PinTransforms.Apply(rotationSample,0,true,false);horizontal.CopyPixels(rotatedBytes,12,0);Check(rotatedBytes[0]==3&&rotatedBytes[8]==1&&rotatedBytes[12]==6,"horizontal flip mirrors on screen axis");var vertical=PinTransforms.Apply(rotationSample,0,false,true);vertical.CopyPixels(rotatedBytes,12,0);Check(rotatedBytes[0]==4&&rotatedBytes[12]==1,"vertical flip mirrors on screen axis");
        for(int i=0;i<3;i++)rotated=PinTransforms.Apply(rotated,1,false,false);rotated.CopyPixels(rotatedBytes,12,0);Check(samplePixels.SequenceEqual(rotatedBytes),"four rotations retain all original pixels");
        bool composed=true;for(int turns=0;turns<4;turns++)foreach(bool h in new[]{false,true})foreach(bool v in new[]{false,true})foreach(int direction in new[]{-1,1}){var orientation=new PinRecord{QuarterTurns=turns,FlipHorizontal=h,FlipVertical=v};var before=PinTransforms.Apply(rotationSample,turns,h,v);var expected=PinTransforms.Apply(before,direction,false,false);PinTransforms.Rotate(orientation,direction);var actual=PinTransforms.Apply(rotationSample,orientation.QuarterTurns,orientation.FlipHorizontal,orientation.FlipVertical);var a=new byte[24];var b=new byte[24];actual.CopyPixels(a,actual.PixelWidth*4,0);expected.CopyPixels(b,expected.PixelWidth*4,0);composed&=a.SequenceEqual(b);}Check(composed,"rotate after either mirror follows visible screen direction");
        Check(PinToolbar.Button("rotate","旋转 / 翻转",()=>{}).Width==26,"external toolbar buttons reduced to 26 DIP");Check(((BitmapSource)Ui.AppIcon).PixelWidth==256,"new application icon embedded in executable");
        var crop=Geometry.PixelCrop(new Rect(-3,-4,25,30),1.5,1.5,100,80);Check(crop.X==0&&crop.Y==0&&crop.Width==33&&crop.Height==39,"DPI crop clamps to image");
        var words=new[]{new WordBox{Text="Hello",Line=0},new WordBox{Text="world",Line=0},new WordBox{Text="你",Line=1},new WordBox{Text="好",Line=1}};Check(Geometry.JoinWords(words)=="Hello world"+Environment.NewLine+"你好","selected words reading order");
        var visual=new DrawingVisual();using(var d=visual.RenderOpen()){d.DrawRectangle(Brushes.White,null,new Rect(0,0,600,180));d.DrawText(new FormattedText("Save the screenshot",System.Globalization.CultureInfo.InvariantCulture,FlowDirection.LeftToRight,new Typeface("Arial"),30,Brushes.Black),new Point(20,35));}
        var bitmap=new RenderTargetBitmap(600,180,96,96,PixelFormats.Pbgra32);bitmap.Render(visual);bitmap.Freeze();
        var indexed=new OcrPage();indexed.Words.AddRange(words);OcrService.IndexText(indexed);Check(indexed.Text=="Hello world"+Environment.NewLine+"你好","OCR sidebar retains all lines");Check(indexed.Words.All(w=>indexed.Text.Substring(w.TextStart,w.Text.Length)==w.Text),"word selection offsets match complete transcript");
        var ocrCache=new OcrResultCache();ocrCache.Put("one",indexed);var ocrCopy=ocrCache.Get("one");ocrCopy.Words[0].Text="mutated";Check(ocrCache.Get("one").Words[0].Text=="Hello"&&ocrCache.Get("different")==null,"OCR transcript cache is keyed and does not share mutable word boxes");Check(OcrResultCache.Fingerprint(bitmap,CancellationToken.None)==OcrResultCache.Fingerprint(bitmap.Clone(),CancellationToken.None),"identical pixels reuse OCR across different bitmap objects");
        var koreanWords=new OcrPage();koreanWords.Words.AddRange(new[]{new WordBox{Text="새로운",Line=0},new WordBox{Text="경험",Line=0},new WordBox{Text="Camera",Line=1},new WordBox{Text="설정",Line=1}});OcrService.IndexText(koreanWords);Check(koreanWords.Text=="새로운 경험"+Environment.NewLine+"Camera 설정"&&Geometry.JoinWords(koreanWords.Words)==koreanWords.Text,"Korean word spacing preserved in transcript and selection");Check(koreanWords.Words.All(w=>koreanWords.Text.Substring(w.TextStart,w.Text.Length)==w.Text),"Korean selected-text offsets match transcript");
        var surface=new ScreenshotSurface{Image=bitmap,Selection=new Rect(0,0,300,90)};surface.Measure(new Size(300,90));surface.Arrange(new Rect(0,0,300,90));surface.Marks.Add(new Annotation{Kind="rect",Start=new Point(5,5),End=new Point(100,80),Width=3});var exported=surface.Export();Check(exported.PixelWidth==600&&exported.PixelHeight==180,"annotated export preserves physical pixels");
        byte[] pixel=new byte[4];exported.CopyPixels(new Int32Rect(100,140,1,1),pixel,4,0);Check(pixel[0]==255&&pixel[1]==255&&pixel[2]==255,"rectangle center remains unfilled");
        surface.BrushPoint=new Point(120,70);surface.BrushDiameter=21;surface.ShowBrushSize=true;var withCursor=surface.Export();withCursor.CopyPixels(new Int32Rect(240,140,1,1),pixel,4,0);Check(pixel[0]==255&&pixel[1]==255&&pixel[2]==255,"brush-size preview excluded from screenshot export");
        var translatedVisual=new DrawingVisual();using(var d=translatedVisual.RenderOpen())d.DrawRectangle(Brushes.Green,null,new Rect(0,0,200,80));var translatedSample=new RenderTargetBitmap(200,80,96,96,PixelFormats.Pbgra32);translatedSample.Render(translatedVisual);translatedSample.Freeze();
        surface.Selection=new Rect(50,30,100,40);surface.TranslationBounds=surface.Selection;surface.TranslationImage=translatedSample;surface.ShowTranslation=true;
        var previewExport=surface.Export(false);previewExport.CopyPixels(new Int32Rect(100,40,1,1),pixel,4,0);Check(previewExport.PixelWidth==200&&previewExport.PixelHeight==80&&pixel[1]==128&&pixel[2]==0,"in-place translation export respects offset selection and DPI");
        surface.Export(false,false).CopyPixels(new Int32Rect(100,40,1,1),pixel,4,0);Check(pixel[2]==255,"OCR always reads original, not previous translation");
        surface.ShowTranslation=false;surface.Export(false).CopyPixels(new Int32Rect(100,40,1,1),pixel,4,0);Check(pixel[2]==255,"translation toggle restores original export");surface.ClearTranslation();Check(surface.TranslationImage==null&&!surface.ShowTranslation,"changing selection clears translated preview");
        var folder=Path.Combine(Path.GetTempPath(),"QingJie-Test-"+Guid.NewGuid().ToString("N"));var store=new PinStore(folder);var pin=store.Add(bitmap);pin.Left=-1200;pin.Top=80;pin.Width=410;pin.Opacity=.7;store.Save();var second=new PinStore(folder);Check(second.Records.Count==1&&second.Records[0].Active&&second.Records[0].Left==-1200,"active pin survives restart with placement");second.Records[0].Active=false;second.Records[0].ClosedAt=DateTime.UtcNow.Ticks;second.Save();var third=new PinStore(folder);Check(third.LastClosed()!=null&&File.Exists(third.ImagePath(third.LastClosed())),"closed pin remains recoverable");
        var visualRecord=new PinRecord{Id=Guid.NewGuid().ToString("N"),Left=200,Top=200,Width=410};var decoratedPin=new PinWindow(store,visualRecord,bitmap);decoratedPin.UpdateRecord();Check(visualRecord.Left==200&&visualRecord.Top==200&&visualRecord.Width==410,"shadow margin does not shift persisted image position or scale");Check(decoratedPin.AllowsTransparency&&decoratedPin.Width==434&&Math.Abs(decoratedPin.Height-(410*.3+24))<.001,"pin reserves transparent shadow space without changing image aspect ratio");decoratedPin.Close();
        var picture=new System.Windows.Controls.Image{Source=bitmap,Stretch=Stretch.Fill};var pinFrame=new PinFrame(picture);
        var previewRoot=new System.Windows.Controls.Grid{Background=new SolidColorBrush(Color.FromRgb(236,239,242))};previewRoot.Children.Add(pinFrame);pinFrame.Margin=new Thickness(20);previewRoot.Measure(new Size(664,244));previewRoot.Arrange(new Rect(0,0,664,244));previewRoot.UpdateLayout();
        var idlePreview=new RenderTargetBitmap(664,244,96,96,PixelFormats.Pbgra32);idlePreview.Render(previewRoot);ImageFiles.Write(idlePreview,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"pin-shadow-idle.png"));pinFrame.SetHovered(true);previewRoot.UpdateLayout();var hoverPreview=new RenderTargetBitmap(664,244,96,96,PixelFormats.Pbgra32);hoverPreview.Render(previewRoot);ImageFiles.Write(hoverPreview,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"pin-shadow-hover.png"));
        Check(picture.Effect==null&&ReferenceEquals(picture.Source,bitmap),"hover glow decorates only the frame and never changes saved image pixels");
        Check(third.Records[0].Width==410&&third.Records[0].Opacity==.7,"pin zoom and opacity persist");
        third.Records[0].QuarterTurns=3;third.Records[0].FlipHorizontal=true;third.Records[0].FlipVertical=true;third.Save();var orientationStore=new PinStore(folder);Check(orientationStore.Records[0].QuarterTurns==3&&orientationStore.Records[0].FlipHorizontal&&orientationStore.Records[0].FlipVertical,"rotation and both mirror states survive restart and recovery");
        third.Records[0].IsTranslation=true;third.SaveTranslation(third.Records[0],bitmap);var translatedPin=new PinStore(folder);Check(translatedPin.Records[0].IsTranslation&&File.Exists(translatedPin.TranslationPath(translatedPin.Records[0]))&&File.Exists(translatedPin.ImagePath(translatedPin.Records[0])),"translated pin and original are saved separately");
        third.Save();File.WriteAllText(Path.Combine(folder,"pins.json"),"{interrupted");var recovered=new PinStore(folder);Check(recovered.Records.Count==1&&recovered.LastClosed()!=null,"corrupt pin index recovers from atomic backup");
        File.WriteAllText(Path.Combine(folder,"pins.json.bak"),"{also broken");var orphaned=new PinStore(folder);Check(orphaned.LastClosed()!=null,"orphaned PNG stays recoverable if both indexes fail");orphaned.Save();Check(new PinStore(folder).LastClosed()!=null,"recovered index can be saved again");
        // Only test-generated files in a fresh random temporary directory are removed.
        foreach(var file in Directory.GetFiles(folder))File.Delete(file);Directory.Delete(folder);
        Console.WriteLine("OCR languages: "+OcrService.Languages());
        var frame=new System.Windows.Threading.DispatcherFrame();OcrPage page=null;Exception error=null;
        var task=OcrService.Read(bitmap);task.ContinueWith(t=>{if(t.IsFaulted)error=t.Exception;else page=t.Result;System.Windows.Threading.Dispatcher.CurrentDispatcher.BeginInvoke(new Action(()=>{}));frame.Continue=false;});System.Windows.Threading.Dispatcher.PushFrame(frame);
        if(error!=null)throw error;Check(page!=null&&page.Text.ToLowerInvariant().Contains("screenshot"),"local Windows OCR recognizes synthetic English sample");
        var regions=ImageTranslation.Regions(page);Check(regions.Count==1,"OCR sample creates one image translation region");
        var imageTranslation=ImageTranslation.Render(bitmap,regions,new[]{"保存截图"});Check(imageTranslation.PixelWidth==600&&imageTranslation.PixelHeight==180,"image translation preserves original dimensions");imageTranslation.CopyPixels(new Int32Rect(550,140,1,1),pixel,4,0);Check(pixel[0]==255&&pixel[1]==255&&pixel[2]==255,"image translation leaves non-text background intact");
        ImageFiles.Write(imageTranslation,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"translation-preview.png"));
        var labels=new OcrPage();labels.Words.Add(new WordBox{Text="Save",Line=0,Box=new Rect(20,20,80,20)});labels.Words.Add(new WordBox{Text="Pin",Line=1,Box=new Rect(20,100,80,20)});Check(ImageTranslation.Regions(labels).Count==2,"separate labels retain separate positions");labels.Words[1].Box=new Rect(20,47,80,20);Check(ImageTranslation.Regions(labels).Count==1,"nearby paragraph lines translate together");labels.Words[1].Line=0;labels.Words[1].Box=new Rect(300,20,80,20);Check(ImageTranslation.Regions(labels).Count==2,"distant columns do not merge");
        var parsed=Translation.ParseResponse("{\"header\":{\"ret_code\":\"succ\"},\"auto_translation\":[\"保存\",\"贴图\"]}",2);Check(parsed.SequenceEqual(new[]{"保存","贴图"}),"batched translations preserve region order");bool rejected=false;try{Translation.ParseResponse("{\"header\":{\"ret_code\":\"succ\"},\"auto_translation\":[\"保存\"]}",2);}catch(InvalidOperationException){rejected=true;}Check(rejected,"incomplete translation never painted over original");
        var darkVisual=new DrawingVisual();using(var d=darkVisual.RenderOpen()){
            d.DrawRectangle(new SolidColorBrush(Color.FromRgb(9,9,9)),null,new Rect(0,0,960,420));
            string[] labelsText={"Ready. Create. Fold.","Gimbal first, then body up. Body down, then gimbal folds.","Manually adjustable mast","Set camera height by hand, independent of wheel lifts."};
            for(int i=0;i<labelsText.Length;i++)d.DrawText(new FormattedText(labelsText[i],System.Globalization.CultureInfo.InvariantCulture,FlowDirection.LeftToRight,new Typeface("Segoe UI"),i%2==0?18:16,Brushes.White,1),new Point(80,60+i*60));
        }
        var darkImage=new RenderTargetBitmap(960,420,96,96,PixelFormats.Pbgra32);darkImage.Render(darkVisual);darkImage.Freeze();ImageFiles.Write(darkImage,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"english-dark-test.png"));
        var english=Await(OcrService.Read(darkImage));Check(english.Text.Contains("Ready. Create. Fold."),"small dark-background Fold recognized by local English model");Check(english.Text.Contains("Manually adjustable mast"),"small English heading no longer becomes mixed symbols");
        Check(SamePixels(LegacyPrepare(darkImage,3),OcrService.Prepare(darkImage,3)),"dark small-text preprocessing retains every grayscale pixel");
        var inProcess=Await(OcrService.ReadLocal(darkImage));Check(english.Text==inProcess.Text&&english.Words.Zip(inProcess.Words,(a,b)=>a.Text==b.Text&&a.Line==b.Line&&a.Box==b.Box).All(v=>v)&&english.Words.Count==inProcess.Words.Count,"isolated OCR preserves text, reading order and exact word positions");
        using(var cancelled=new CancellationTokenSource()){cancelled.Cancel();bool stopped=false;try{Await(OcrService.Read(darkImage,cancelled.Token));}catch(OperationCanceledException){stopped=true;}Check(stopped,"cancelled OCR never starts work");}
        using(var cancelled=new CancellationTokenSource()){cancelled.CancelAfter(30);bool stopped=false;try{Await(OcrService.Read(new CroppedBitmap(darkImage,new Int32Rect(0,0,959,420)),cancelled.Token));}catch(OperationCanceledException){stopped=true;}Check(stopped,"active OCR cancellation terminates worker");}
        var queued=Await(Task.WhenAll(OcrService.Read(darkImage),OcrService.Read(darkImage)));Check(queued.All(p=>p.Text==english.Text),"queued OCR requests keep identical independent results after cancellation");
        bool workerLeft=false;foreach(var process in System.Diagnostics.Process.GetProcessesByName("QingJie")){using(process){try{if(string.Equals(process.MainModule.FileName,typeof(Program).Assembly.Location,StringComparison.OrdinalIgnoreCase))workerLeft=true;}catch{}}}Check(!workerLeft,"OCR leaves no worker process or retained OCR engine");
        var mixedVisual=new DrawingVisual();using(var d=mixedVisual.RenderOpen()){d.DrawRectangle(Brushes.White,null,new Rect(0,0,1000,260));d.DrawText(new FormattedText("截图翻译 测试 / Camera height 120 mm",System.Globalization.CultureInfo.GetCultureInfo("zh-CN"),FlowDirection.LeftToRight,new Typeface("Microsoft YaHei UI"),24,Brushes.Black,1),new Point(30,50));d.DrawText(new FormattedText("保存图片  水平翻转  Rotate 90",System.Globalization.CultureInfo.GetCultureInfo("zh-CN"),FlowDirection.LeftToRight,new Typeface("Microsoft YaHei UI"),24,Brushes.Black,1),new Point(30,110));}var mixed=new RenderTargetBitmap(1000,260,96,96,PixelFormats.Pbgra32);mixed.Render(mixedVisual);mixed.Freeze();ImageFiles.Write(mixed,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"mixed-test.png"));Check(SamePixels(LegacyPrepare(mixed,2.5),OcrService.Prepare(mixed,2.5)),"mixed Chinese-English preprocessing retains pixel values");var mixedText=Await(OcrService.Read(mixed));Check(mixedText.Text.Contains("截图翻译")&&mixedText.Text.Contains("Camera")&&mixedText.Text.Contains("保存图片"),"mixed Chinese-English OCR quality retained");
        Check(english.Words.All(w=>w.Box.X>=0&&w.Box.Y>=0&&w.Box.Right<=960&&w.Box.Bottom<=420),"upscaled OCR maps boxes back to original image coordinates");
        var koreanVisual=new DrawingVisual();using(var d=koreanVisual.RenderOpen()){
            d.DrawRectangle(new SolidColorBrush(Color.FromRgb(245,245,245)),null,new Rect(0,0,1100,260));
            d.DrawText(new FormattedText("Back to Retro.",System.Globalization.CultureInfo.InvariantCulture,FlowDirection.LeftToRight,new Typeface("Arial"),32,Brushes.Navy),new Point(20,20));
            string[] koreanLines={"새로운 경험을 위해 제품을 디자인했습니다.","제품 사용 시 새로운 인상을 남길 수 있습니다."};
            for(int i=0;i<2;i++)d.DrawText(new FormattedText(koreanLines[i],System.Globalization.CultureInfo.GetCultureInfo("ko-KR"),FlowDirection.LeftToRight,new Typeface("Malgun Gothic"),14,new SolidColorBrush(Color.FromRgb(184,184,184))),new Point(20,100+i*26));
        }
        OcrLanguagePacks.TestSelection="kor";
        var koreanImage=new RenderTargetBitmap(1100,260,96,96,PixelFormats.Pbgra32);koreanImage.Render(koreanVisual);koreanImage.Freeze();ImageFiles.Write(koreanImage,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"korean-test.png"));var koreanText=Await(OcrService.Read(koreanImage));Console.WriteLine(koreanText.Text);Check(koreanText.Text.Contains("새로운 경험")&&koreanText.Text.Contains("제품 사용"),"faint small Korean paragraphs recognized with natural word spacing");Check(koreanText.Text.Contains("Back to Retro."),"Korean pass preserves existing English heading");Check(!Await(OcrService.Read(mixed)).Text.Any(Geometry.IsHangul),"Korean pass never replaces Chinese regression sample");Check(koreanText.Words.All(w=>w.Box.X>=0&&w.Box.Y>=0&&w.Box.Right<=1100&&w.Box.Bottom<=260),"Korean word boxes retain original coordinates");
        Check(Translation.ParseImageContext("[[[0000]]]\n保存\n\n[[[0001]]]\n贴图",2).SequenceEqual(new[]{"保存","贴图"}),"context-aware translation maps back to source regions");
        Check(Translation.ParseImageContext("[0000]\n保存\n\n[0001]\n贴图",2).SequenceEqual(new[]{"保存","贴图"}),"translation accepts normalized marker brackets");
        Check(Translation.SourceLanguage("새로운 경험을 위해") == "ko"&&Translation.SourceLanguage("Save the screenshot")=="auto","Korean translation explicitly selects Korean source language");
        var bilingual=new OcrPage();bilingual.Words.Add(new WordBox{Text="새로운 경험",Line=0,Box=new Rect(20,20,150,20)});bilingual.Words.Add(new WordBox{Text="New experience",Line=1,Box=new Rect(20,47,150,20)});Check(ImageTranslation.Regions(bilingual).Count==2,"adjacent Korean and English paragraphs translate separately");
        foreach(var shade in new[]{Colors.Black,Color.FromRgb(184,184,184)}){
            var chineseVisual=new DrawingVisual();using(var d=chineseVisual.RenderOpen()){d.DrawRectangle(Brushes.White,null,new Rect(0,0,1000,230));string[] chineseLines={"中文截图翻译，保留原来的识别效果。","保存图片和屏幕贴图，可以随时恢复。","新的设计让日常生活更加方便。"};for(int i=0;i<chineseLines.Length;i++)d.DrawText(new FormattedText(chineseLines[i],System.Globalization.CultureInfo.GetCultureInfo("zh-CN"),FlowDirection.LeftToRight,new Typeface("Microsoft YaHei"),18,new SolidColorBrush(shade),1),new Point(20,20+i*50));}
            var chineseImage=new RenderTargetBitmap(1000,230,96,96,PixelFormats.Pbgra32);chineseImage.Render(chineseVisual);chineseImage.Freeze();var chineseText=Await(OcrService.Read(chineseImage));Check(chineseText.Text.Contains("保存图片")&&chineseText.Text.Contains("日常生活")&&!chineseText.Text.Any(Geometry.IsHangul),"Chinese paragraphs protected at shade "+shade);
        }
        var languageSamples=new[]{
            new[]{"jpn","画像を保存してください。新しいデザインです。","画像","Yu Gothic"},new[]{"rus","Сохранить изображение. Новый дизайн.","Сохранить","Segoe UI"},
            new[]{"fra","Enregistrer une image. Nouvelle expérience.","Enregistrer","Segoe UI"},new[]{"deu","Bild speichern. Neue Möglichkeiten.","speichern","Segoe UI"},
            new[]{"spa","Guardar imagen. Nueva experiencia.","Guardar","Segoe UI"},new[]{"por","Salvar imagem. Nova experiência.","Salvar","Segoe UI"},new[]{"ita","Salva immagine. Nuova esperienza.","Salva","Segoe UI"},
            new[]{"ara","حفظ الصورة وترجمة النص","الصورة","Segoe UI"},new[]{"tha","บันทึกภาพและแปลข้อความ","ภาพ","Leelawadee UI"},new[]{"vie","Lưu hình ảnh và dịch văn bản","hình","Segoe UI"}
        };
        foreach(var sample in languageSamples){
            var pack=OcrLanguagePacks.Find(sample[0]);Check(OcrLanguagePacks.Verify(OcrLanguagePacks.ModelPath(pack.Id),pack),pack.Name+" pinned model checksum");OcrLanguagePacks.TestSelection=pack.Id;
            var languageVisual=new DrawingVisual();using(var d=languageVisual.RenderOpen()){d.DrawRectangle(Brushes.White,null,new Rect(0,0,1000,200));d.DrawText(new FormattedText(sample[1],System.Globalization.CultureInfo.InvariantCulture,sample[0]=="ara"?FlowDirection.RightToLeft:FlowDirection.LeftToRight,new Typeface(sample[3]),24,Brushes.Black,1),new Point(sample[0]=="ara"?900:20,50));}
            var languageImage=new RenderTargetBitmap(1000,200,96,96,PixelFormats.Pbgra32);languageImage.Render(languageVisual);languageImage.Freeze();var languageText=Await(OcrService.Read(languageImage));Console.WriteLine(pack.Id+": "+languageText.Text);Check(languageText.Text.Contains(sample[2]),pack.Name+" optional model recognizes synthetic sample");
        }
        OcrLanguagePacks.TestSelection="";Check(OcrLanguagePacks.SelectedId=="","English remains default with optional models installed");
        var defaultEnglish=Await(OcrService.Read(darkImage));Check(defaultEnglish.Text==english.Text,"switching back to English preserves original OCR result");
        var packTestFolder=Path.Combine(Path.GetTempPath(),"QingJie-Languages-Test-"+Guid.NewGuid().ToString("N"));var modelSource=OcrLanguagePacks.ModelPath("fra");OcrLanguagePacks.TestFolder=packTestFolder;
        try{
            OcrLanguagePacks.Import(modelSource,"fra");Check(OcrLanguagePacks.Installed("fra")&&OcrLanguagePacks.Verify(OcrLanguagePacks.ModelPath("fra"),OcrLanguagePacks.Find("fra")),"optional model imports atomically with checksum verification");
            var badModel=Path.Combine(packTestFolder,"bad.traineddata");File.WriteAllText(badModel,"invalid model");bool badModelRejected=false;try{OcrLanguagePacks.Import(badModel,"fra");}catch(InvalidOperationException){badModelRejected=true;}Check(badModelRejected&&OcrLanguagePacks.Verify(OcrLanguagePacks.ModelPath("fra"),OcrLanguagePacks.Find("fra")),"invalid language import cannot overwrite a working model");
            using(var modelCancel=new CancellationTokenSource()){modelCancel.Cancel();bool stopped=false;try{Await(OcrLanguagePacks.Install("jpn",null,modelCancel.Token).ContinueWith(t=>{t.GetAwaiter().GetResult();return true;}));}catch(OperationCanceledException){stopped=true;}Check(stopped&&!OcrLanguagePacks.Installed("jpn"),"cancelled model download leaves no partial installed model");}
            if(Environment.GetEnvironmentVariable("QINGJIE_LIVE_TEST")=="1"){Await(OcrLanguagePacks.Install("fra",null,CancellationToken.None).ContinueWith(t=>{t.GetAwaiter().GetResult();return true;}));Check(OcrLanguagePacks.Verify(OcrLanguagePacks.ModelPath("fra"),OcrLanguagePacks.Find("fra")),"live optional model download verifies pinned content");}
        }finally{OcrLanguagePacks.TestFolder=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"test-languages");foreach(var file in Directory.GetFiles(packTestFolder))File.Delete(file);Directory.Delete(packTestFolder);}
        Check(Translation.DeviceTerms(new[]{"Fold your poker cards."},new[]{"弃牌。"})[0]=="弃牌。","equipment glossary does not alter unrelated meanings");
        bool wrongOrder=false;try{Translation.ParseImageContext("[[[0001]]]\n错位",1);}catch(InvalidOperationException){wrongOrder=true;}Check(wrongOrder,"incorrect translation region markers leave original intact");
        if(Environment.GetEnvironmentVariable("QINGJIE_LIVE_TEST")=="1"){var input=ImageTranslation.Regions(english);var translation=Translation.TranslateImage(input.Select(r=>r.Text).ToArray(),CancellationToken.None).GetAwaiter().GetResult();Console.WriteLine(string.Join(" | ",translation));Check(translation[0].Contains("折叠"),"Fold correctly translated to Chinese with image context via live service");Check(translation.Any(t=>t.Contains("手动")),"adjustable mast heading translated without OCR corruption");ImageFiles.Write(ImageTranslation.Render(darkImage,input,translation),Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"english-live-translation.png"));var multilingual=Translation.TranslateImage(new[]{"Back to Retro.","새로운 경험을 위해 제품을 디자인했습니다.","Save the screenshot"},CancellationToken.None).GetAwaiter().GetResult();Console.WriteLine(string.Join(" | ",multilingual));Check(multilingual.Length==3&&!multilingual.Any(t=>t.Any(Geometry.IsHangul))&&multilingual[1].Contains("产品")&&multilingual[2].Contains("截图"),"Korean-English mixed image translates each language to Chinese in order");var selected=Translation.Translate("제품 사용",CancellationToken.None).GetAwaiter().GetResult();Check(!selected.Any(Geometry.IsHangul)&&selected.Contains("产品"),"Korean selected-text translation uses explicit source");}
        if(Environment.GetEnvironmentVariable("QINGJIE_LIVE_TEST")=="1"){
            string englishReply=Translation.Translate("请确认交货日期，谢谢。",CancellationToken.None,"en").GetAwaiter().GetResult();Console.WriteLine("Chinese to English: "+englishReply);Check(System.Text.RegularExpressions.Regex.IsMatch(englishReply,"[a-zA-Z]{3}")&&!System.Text.RegularExpressions.Regex.IsMatch(englishReply,"[\\u4e00-\\u9fff]"),"live typed Chinese translates into English");
            string backToChinese=Translation.Translate(englishReply,CancellationToken.None).GetAwaiter().GetResult();Check(backToChinese.Contains("日期"),"default English to Chinese remains working");
            var imageEnglish=Translation.TranslateImage(new[]{"保存图片","复制文字"},CancellationToken.None,"en").GetAwaiter().GetResult();Console.WriteLine("Chinese image: "+string.Join(" | ",imageEnglish));Check(imageEnglish.Length==2&&imageEnglish.All(t=>System.Text.RegularExpressions.Regex.IsMatch(t,"[a-zA-Z]{3}")&&!System.Text.RegularExpressions.Regex.IsMatch(t,"[\\u4e00-\\u9fff]")),"live Chinese screenshot regions translate to English in order");
            var mixedRegions=ImageTranslation.Regions(mixedText);var mixedEnglish=Translation.TranslateImage(mixedRegions.Select(r=>r.Text).ToArray(),CancellationToken.None,"en").GetAwaiter().GetResult();var englishPicture=ImageTranslation.Render(mixed,mixedRegions,mixedEnglish);ImageFiles.Write(englishPicture,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"chinese-to-english-test.png"));
            Check(englishPicture.PixelWidth==mixed.PixelWidth&&englishPicture.PixelHeight==mixed.PixelHeight&&mixedEnglish.All(t=>!System.Text.RegularExpressions.Regex.IsMatch(t,"[\\u4e00-\\u9fff]")),"Chinese-English screenshot OCR translates and renders English at original size");
            englishPicture.CopyPixels(new Int32Rect(900,220,1,1),pixel,4,0);Check(pixel[0]==255&&pixel[1]==255&&pixel[2]==255,"Chinese-to-English rendering keeps non-text background untouched");
        }
        Console.WriteLine(count+" tests passed.");return 0;
    }catch(Exception e){Console.Error.WriteLine(e);return 1;}}
}
