using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using QingJie;
using Geometry = QingJie.Geometry;
class Tests {
    static int count;
    static void Check(bool condition,string name){if(!condition)throw new Exception(name);Console.WriteLine("PASS "+name);count++;}
    static T Await<T>(Task<T> task){var frame=new System.Windows.Threading.DispatcherFrame();task.ContinueWith(t=>frame.Continue=false);System.Windows.Threading.Dispatcher.PushFrame(frame);return task.GetAwaiter().GetResult();}
    static BitmapSource LegacyPrepare(BitmapSource source,double ratio){
        var bgra=new FormatConvertedBitmap(source,PixelFormats.Bgra32,null,0);int width=source.PixelWidth,height=source.PixelHeight;var pixels=new byte[width*height*4];bgra.CopyPixels(pixels,width*4,0);
        int dark=0,samples=0;for(int i=0;i<pixels.Length;i+=64){if(pixels[i]*.0722+pixels[i+1]*.7152+pixels[i+2]*.2126<100)dark++;samples++;}
        for(int i=0;i<pixels.Length;i+=4){int gray=(int)(pixels[i]*.0722+pixels[i+1]*.7152+pixels[i+2]*.2126);gray=(gray*pixels[i+3]+255*(255-pixels[i+3]))/255;if(dark>samples*.6)gray=255-gray;pixels[i]=pixels[i+1]=pixels[i+2]=(byte)gray;pixels[i+3]=255;}
        var normalized=BitmapSource.Create(width,height,96,96,PixelFormats.Bgra32,null,pixels,width*4);normalized.Freeze();var scaled=new TransformedBitmap(normalized,new ScaleTransform(ratio,ratio));scaled.Freeze();return scaled;
    }
    static bool SamePixels(BitmapSource a,BitmapSource b){if(a.PixelWidth!=b.PixelWidth||a.PixelHeight!=b.PixelHeight)return false;var bytesA=new byte[a.PixelWidth*a.PixelHeight*4];var bytesB=new byte[bytesA.Length];new FormatConvertedBitmap(a,PixelFormats.Bgra32,null,0).CopyPixels(bytesA,a.PixelWidth*4,0);new FormatConvertedBitmap(b,PixelFormats.Bgra32,null,0).CopyPixels(bytesB,b.PixelWidth*4,0);return bytesA.SequenceEqual(bytesB);}
    [STAThread] static int Main(string[] args){try{
        if(args.Length==2&&args[0]=="--ocr-image"){Console.WriteLine("OCR languages: "+OcrService.Languages());Console.WriteLine(Await(OcrService.Read(Snapshot.Load(args[1]))).Text);return 0;}
        if(args.Length==1&&args[0]=="--context-probe"){Console.WriteLine(Translation.Translate("[[[0000]]]\nReady. Create. Fold.\n\n[[[0001]]]\nGimbal first, then body up. Body down, then gimbal folds.\n\n[[[0002]]]\nManually adjustable mast\n\n[[[0003]]]\nSet camera height by hand, independent of wheel lifts.",CancellationToken.None).GetAwaiter().GetResult());return 0;}
        Check(Geometry.Clamp(30,1,25)==25&&Geometry.Clamp(-2,1,25)==1,"line width clamped");
        var alphaPixels=new byte[33*27*4];new Random(41).NextBytes(alphaPixels);var alphaSample=BitmapSource.Create(33,27,96,96,PixelFormats.Bgra32,null,alphaPixels,33*4);alphaSample.Freeze();
        foreach(double ratio in new[]{.5,1,2.5,3})Check(SamePixels(LegacyPrepare(alphaSample,ratio),OcrService.Prepare(alphaSample,ratio)),"compact grayscale is pixel-identical for alpha/color at scale "+ratio);
        var startupFolder=Path.Combine(Path.GetTempPath(),"QingJie-Startup-Test-"+Guid.NewGuid().ToString("N"));
        var startup=new StartupRegistration(startupFolder,typeof(Program).Assembly.Location);
        Check(!startup.Enabled,"startup is off when shortcut absent");startup.SetEnabled(true);Check(startup.Enabled,"startup enable creates own shortcut");startup.SetEnabled(true);Check(startup.Enabled,"startup enable is idempotent");startup.SetEnabled(false);Check(!startup.Enabled&&!File.Exists(startup.ShortcutPath),"startup disable removes only own shortcut");
        var otherStartup=new StartupRegistration(startupFolder,Path.Combine(startupFolder,"Other.exe"));otherStartup.SetEnabled(true);bool protectedShortcut=false;try{startup.SetEnabled(false);}catch(InvalidOperationException){protectedShortcut=true;}Check(protectedShortcut&&otherStartup.Enabled,"unrelated startup shortcut is protected");otherStartup.SetEnabled(false);Directory.Delete(startupFolder);
        var reverse=Geometry.FromPoints(new Point(80,40),new Point(20,10));Check(reverse.Width==60&&reverse.Height==30,"reverse drag selection");
        var samplePixels=new byte[]{1,0,0,255,2,0,0,255,3,0,0,255,4,0,0,255,5,0,0,255,6,0,0,255};var rotationSample=BitmapSource.Create(3,2,96,96,PixelFormats.Bgra32,null,samplePixels,12);rotationSample.Freeze();
        var rotated=PinTransforms.Apply(rotationSample,1,false,false);var rotatedBytes=new byte[24];rotated.CopyPixels(rotatedBytes,8,0);Check(rotated.PixelWidth==2&&rotated.PixelHeight==3&&new[]{rotatedBytes[0],rotatedBytes[4],rotatedBytes[8],rotatedBytes[12],rotatedBytes[16],rotatedBytes[20]}.SequenceEqual(new byte[]{4,1,5,2,6,3}),"clockwise rotation is pixel exact and swaps dimensions");
        var horizontal=PinTransforms.Apply(rotationSample,0,true,false);horizontal.CopyPixels(rotatedBytes,12,0);Check(rotatedBytes[0]==3&&rotatedBytes[8]==1&&rotatedBytes[12]==6,"horizontal flip mirrors on screen axis");var vertical=PinTransforms.Apply(rotationSample,0,false,true);vertical.CopyPixels(rotatedBytes,12,0);Check(rotatedBytes[0]==4&&rotatedBytes[12]==1,"vertical flip mirrors on screen axis");
        for(int i=0;i<3;i++)rotated=PinTransforms.Apply(rotated,1,false,false);rotated.CopyPixels(rotatedBytes,12,0);Check(samplePixels.SequenceEqual(rotatedBytes),"four rotations retain all original pixels");
        bool composed=true;for(int turns=0;turns<4;turns++)foreach(bool h in new[]{false,true})foreach(bool v in new[]{false,true})foreach(int direction in new[]{-1,1}){var orientation=new PinRecord{QuarterTurns=turns,FlipHorizontal=h,FlipVertical=v};var before=PinTransforms.Apply(rotationSample,turns,h,v);var expected=PinTransforms.Apply(before,direction,false,false);PinTransforms.Rotate(orientation,direction);var actual=PinTransforms.Apply(rotationSample,orientation.QuarterTurns,orientation.FlipHorizontal,orientation.FlipVertical);var a=new byte[24];var b=new byte[24];actual.CopyPixels(a,actual.PixelWidth*4,0);expected.CopyPixels(b,expected.PixelWidth*4,0);composed&=a.SequenceEqual(b);}Check(composed,"rotate after either mirror follows visible screen direction");
        Check(PinToolbar.Button("rotate","旋转 / 翻转",()=>{}).Width==26,"external toolbar buttons reduced to 26 DIP");Check(((BitmapSource)Ui.AppIcon).PixelWidth==256,"new application icon embedded in executable");
        var crop=Geometry.PixelCrop(new Rect(-3,-4,25,30),1.5,1.5,100,80);Check(crop.X==0&&crop.Y==0&&crop.Width==33&&crop.Height==39,"DPI crop clamps to image");
        var words=new[]{new WordBox{Text="Hello",Line=0},new WordBox{Text="world",Line=0},new WordBox{Text="你",Line=1},new WordBox{Text="好",Line=1}};Check(Geometry.JoinWords(words)=="Hello world"+Environment.NewLine+"你好","selected words reading order");
        var visual=new DrawingVisual();using(var d=visual.RenderOpen()){d.DrawRectangle(Brushes.White,null,new Rect(0,0,600,180));d.DrawText(new FormattedText("Save the screenshot",System.Globalization.CultureInfo.InvariantCulture,FlowDirection.LeftToRight,new Typeface("Arial"),30,Brushes.Black),new Point(20,35));}
        var bitmap=new RenderTargetBitmap(600,180,96,96,PixelFormats.Pbgra32);bitmap.Render(visual);bitmap.Freeze();
        var indexed=new OcrPage();indexed.Words.AddRange(words);OcrService.IndexText(indexed);Check(indexed.Text=="Hello world"+Environment.NewLine+"你好","OCR sidebar retains all lines");Check(indexed.Words.All(w=>indexed.Text.Substring(w.TextStart,w.Text.Length)==w.Text),"word selection offsets match complete transcript");
        var surface=new ScreenshotSurface{Image=bitmap,Selection=new Rect(0,0,300,90)};surface.Measure(new Size(300,90));surface.Arrange(new Rect(0,0,300,90));surface.Marks.Add(new Annotation{Kind="rect",Start=new Point(5,5),End=new Point(100,80),Width=3});var exported=surface.Export();Check(exported.PixelWidth==600&&exported.PixelHeight==180,"annotated export preserves physical pixels");
        byte[] pixel=new byte[4];exported.CopyPixels(new Int32Rect(100,140,1,1),pixel,4,0);Check(pixel[0]==255&&pixel[1]==255&&pixel[2]==255,"rectangle center remains unfilled");
        surface.BrushPoint=new Point(120,70);surface.BrushDiameter=21;surface.ShowBrushSize=true;var withCursor=surface.Export();withCursor.CopyPixels(new Int32Rect(240,140,1,1),pixel,4,0);Check(pixel[0]==255&&pixel[1]==255&&pixel[2]==255,"brush-size preview excluded from screenshot export");
        var translatedVisual=new DrawingVisual();using(var d=translatedVisual.RenderOpen())d.DrawRectangle(Brushes.Green,null,new Rect(0,0,200,80));var translatedSample=new RenderTargetBitmap(200,80,96,96,PixelFormats.Pbgra32);translatedSample.Render(translatedVisual);translatedSample.Freeze();
        surface.Selection=new Rect(50,30,100,40);surface.TranslationBounds=surface.Selection;surface.TranslationImage=translatedSample;surface.ShowTranslation=true;
        var previewExport=surface.Export(false);previewExport.CopyPixels(new Int32Rect(100,40,1,1),pixel,4,0);Check(previewExport.PixelWidth==200&&previewExport.PixelHeight==80&&pixel[1]==128&&pixel[2]==0,"in-place translation export respects offset selection and DPI");
        surface.Export(false,false).CopyPixels(new Int32Rect(100,40,1,1),pixel,4,0);Check(pixel[2]==255,"OCR always reads original, not previous translation");
        surface.ShowTranslation=false;surface.Export(false).CopyPixels(new Int32Rect(100,40,1,1),pixel,4,0);Check(pixel[2]==255,"translation toggle restores original export");surface.ClearTranslation();Check(surface.TranslationImage==null&&!surface.ShowTranslation,"changing selection clears translated preview");
        var folder=Path.Combine(Path.GetTempPath(),"QingJie-Test-"+Guid.NewGuid().ToString("N"));var store=new PinStore(folder);var pin=store.Add(bitmap);pin.Left=-1200;pin.Top=80;pin.Width=410;pin.Opacity=.7;store.Save();var second=new PinStore(folder);Check(second.Records.Count==1&&second.Records[0].Active&&second.Records[0].Left==-1200,"active pin survives restart with placement");second.Records[0].Active=false;second.Records[0].ClosedAt=DateTime.UtcNow.Ticks;second.Save();var third=new PinStore(folder);Check(third.LastClosed()!=null&&File.Exists(third.ImagePath(third.LastClosed())),"closed pin remains recoverable");
        var visualRecord=new PinRecord{Id=Guid.NewGuid().ToString("N"),Left=200,Top=200,Width=410};var decoratedPin=new PinWindow(store,visualRecord,bitmap);decoratedPin.UpdateRecord();Check(visualRecord.Left==200&&visualRecord.Top==200&&visualRecord.Width==410,"shadow margin does not shift persisted image position or scale");Check(decoratedPin.AllowsTransparency&&decoratedPin.Width==434&&Math.Abs(decoratedPin.Height-(410*.3+24))<.001,"pin reserves transparent shadow space without changing image aspect ratio");decoratedPin.Close();
        var picture=new System.Windows.Controls.Image{Source=bitmap,Stretch=Stretch.Fill};var pinFrame=new PinFrame(picture);
        var previewRoot=new System.Windows.Controls.Grid{Background=new SolidColorBrush(Color.FromRgb(236,239,242))};previewRoot.Children.Add(pinFrame);pinFrame.Margin=new Thickness(20);previewRoot.Measure(new Size(664,244));previewRoot.Arrange(new Rect(0,0,664,244));previewRoot.UpdateLayout();
        var idlePreview=new RenderTargetBitmap(664,244,96,96,PixelFormats.Pbgra32);idlePreview.Render(previewRoot);ImageFiles.Write(idlePreview,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"pin-shadow-idle.png"));pinFrame.SetHovered(true);previewRoot.UpdateLayout();var hoverPreview=new RenderTargetBitmap(664,244,96,96,PixelFormats.Pbgra32);hoverPreview.Render(previewRoot);ImageFiles.Write(hoverPreview,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"pin-shadow-hover.png"));
        Check(picture.Effect==null&&ReferenceEquals(picture.Source,bitmap),"hover glow decorates only the frame and never changes saved image pixels");
        Check(third.Records[0].Width==410&&third.Records[0].Opacity==.7,"pin zoom and opacity persist");
        third.Records[0].QuarterTurns=3;third.Records[0].FlipHorizontal=true;third.Records[0].FlipVertical=true;third.Save();var orientationStore=new PinStore(folder);Check(orientationStore.Records[0].QuarterTurns==3&&orientationStore.Records[0].FlipHorizontal&&orientationStore.Records[0].FlipVertical,"rotation and both mirror states survive restart and recovery");
        third.Records[0].IsTranslation=true;third.SaveTranslation(third.Records[0],bitmap);var translatedPin=new PinStore(folder);Check(translatedPin.Records[0].IsTranslation&&File.Exists(translatedPin.TranslationPath(translatedPin.Records[0]))&&File.Exists(translatedPin.ImagePath(translatedPin.Records[0])),"translated pin and original are saved separately");
        third.Save();File.WriteAllText(Path.Combine(folder,"pins.json"),"{interrupted");var recovered=new PinStore(folder);Check(recovered.Records.Count==1&&recovered.LastClosed()!=null,"corrupt pin index recovers from atomic backup");
        File.WriteAllText(Path.Combine(folder,"pins.json.bak"),"{also broken");var orphaned=new PinStore(folder);Check(orphaned.LastClosed()!=null,"orphaned PNG stays recoverable if both indexes fail");orphaned.Save();Check(new PinStore(folder).LastClosed()!=null,"recovered index can be saved again");
        // Only test-generated files in a fresh random temporary directory are removed.
        foreach(var file in Directory.GetFiles(folder))File.Delete(file);Directory.Delete(folder);
        Console.WriteLine("OCR languages: "+OcrService.Languages());
        var frame=new System.Windows.Threading.DispatcherFrame();OcrPage page=null;Exception error=null;
        var task=OcrService.Read(bitmap);task.ContinueWith(t=>{if(t.IsFaulted)error=t.Exception;else page=t.Result;System.Windows.Threading.Dispatcher.CurrentDispatcher.BeginInvoke(new Action(()=>{}));frame.Continue=false;});System.Windows.Threading.Dispatcher.PushFrame(frame);
        if(error!=null)throw error;Check(page!=null&&page.Text.ToLowerInvariant().Contains("screenshot"),"local Windows OCR recognizes synthetic English sample");
        var regions=ImageTranslation.Regions(page);Check(regions.Count==1,"OCR sample creates one image translation region");
        var imageTranslation=ImageTranslation.Render(bitmap,regions,new[]{"保存截图"});Check(imageTranslation.PixelWidth==600&&imageTranslation.PixelHeight==180,"image translation preserves original dimensions");imageTranslation.CopyPixels(new Int32Rect(550,140,1,1),pixel,4,0);Check(pixel[0]==255&&pixel[1]==255&&pixel[2]==255,"image translation leaves non-text background intact");
        ImageFiles.Write(imageTranslation,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"translation-preview.png"));
        var labels=new OcrPage();labels.Words.Add(new WordBox{Text="Save",Line=0,Box=new Rect(20,20,80,20)});labels.Words.Add(new WordBox{Text="Pin",Line=1,Box=new Rect(20,100,80,20)});Check(ImageTranslation.Regions(labels).Count==2,"separate labels retain separate positions");labels.Words[1].Box=new Rect(20,47,80,20);Check(ImageTranslation.Regions(labels).Count==1,"nearby paragraph lines translate together");labels.Words[1].Line=0;labels.Words[1].Box=new Rect(300,20,80,20);Check(ImageTranslation.Regions(labels).Count==2,"distant columns do not merge");
        var parsed=Translation.ParseResponse("{\"header\":{\"ret_code\":\"succ\"},\"auto_translation\":[\"保存\",\"贴图\"]}",2);Check(parsed.SequenceEqual(new[]{"保存","贴图"}),"batched translations preserve region order");bool rejected=false;try{Translation.ParseResponse("{\"header\":{\"ret_code\":\"succ\"},\"auto_translation\":[\"保存\"]}",2);}catch(InvalidOperationException){rejected=true;}Check(rejected,"incomplete translation never painted over original");
        var darkVisual=new DrawingVisual();using(var d=darkVisual.RenderOpen()){
            d.DrawRectangle(new SolidColorBrush(Color.FromRgb(9,9,9)),null,new Rect(0,0,960,420));
            string[] labelsText={"Ready. Create. Fold.","Gimbal first, then body up. Body down, then gimbal folds.","Manually adjustable mast","Set camera height by hand, independent of wheel lifts."};
            for(int i=0;i<labelsText.Length;i++)d.DrawText(new FormattedText(labelsText[i],System.Globalization.CultureInfo.InvariantCulture,FlowDirection.LeftToRight,new Typeface("Segoe UI"),i%2==0?18:16,Brushes.White,1),new Point(80,60+i*60));
        }
        var darkImage=new RenderTargetBitmap(960,420,96,96,PixelFormats.Pbgra32);darkImage.Render(darkVisual);darkImage.Freeze();ImageFiles.Write(darkImage,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"english-dark-test.png"));
        var english=Await(OcrService.Read(darkImage));Check(english.Text.Contains("Ready. Create. Fold."),"small dark-background Fold recognized by local English model");Check(english.Text.Contains("Manually adjustable mast"),"small English heading no longer becomes mixed symbols");
        Check(SamePixels(LegacyPrepare(darkImage,3),OcrService.Prepare(darkImage,3)),"dark small-text preprocessing retains every grayscale pixel");
        var inProcess=Await(OcrService.ReadLocal(darkImage));Check(english.Text==inProcess.Text&&english.Words.Zip(inProcess.Words,(a,b)=>a.Text==b.Text&&a.Line==b.Line&&a.Box==b.Box).All(v=>v)&&english.Words.Count==inProcess.Words.Count,"isolated OCR preserves text, reading order and exact word positions");
        using(var cancelled=new CancellationTokenSource()){cancelled.Cancel();bool stopped=false;try{Await(OcrService.Read(darkImage,cancelled.Token));}catch(OperationCanceledException){stopped=true;}Check(stopped,"cancelled OCR never starts work");}
        using(var cancelled=new CancellationTokenSource()){cancelled.CancelAfter(30);bool stopped=false;try{Await(OcrService.Read(darkImage,cancelled.Token));}catch(OperationCanceledException){stopped=true;}Check(stopped,"active OCR cancellation terminates worker");}
        var queued=Await(Task.WhenAll(OcrService.Read(darkImage),OcrService.Read(darkImage)));Check(queued.All(p=>p.Text==english.Text),"queued OCR requests keep identical independent results after cancellation");
        bool workerLeft=false;foreach(var process in System.Diagnostics.Process.GetProcessesByName("QingJie")){using(process){try{if(string.Equals(process.MainModule.FileName,typeof(Program).Assembly.Location,StringComparison.OrdinalIgnoreCase))workerLeft=true;}catch{}}}Check(!workerLeft,"OCR leaves no worker process or retained OCR engine");
        var mixedVisual=new DrawingVisual();using(var d=mixedVisual.RenderOpen()){d.DrawRectangle(Brushes.White,null,new Rect(0,0,1000,260));d.DrawText(new FormattedText("截图翻译 测试 / Camera height 120 mm",System.Globalization.CultureInfo.GetCultureInfo("zh-CN"),FlowDirection.LeftToRight,new Typeface("Microsoft YaHei UI"),24,Brushes.Black,1),new Point(30,50));d.DrawText(new FormattedText("保存图片  水平翻转  Rotate 90",System.Globalization.CultureInfo.GetCultureInfo("zh-CN"),FlowDirection.LeftToRight,new Typeface("Microsoft YaHei UI"),24,Brushes.Black,1),new Point(30,110));}var mixed=new RenderTargetBitmap(1000,260,96,96,PixelFormats.Pbgra32);mixed.Render(mixedVisual);mixed.Freeze();ImageFiles.Write(mixed,Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"mixed-test.png"));Check(SamePixels(LegacyPrepare(mixed,2.5),OcrService.Prepare(mixed,2.5)),"mixed Chinese-English preprocessing retains pixel values");var mixedText=Await(OcrService.Read(mixed));Check(mixedText.Text.Contains("截图翻译")&&mixedText.Text.Contains("Camera")&&mixedText.Text.Contains("保存图片"),"mixed Chinese-English OCR quality retained");
        Check(english.Words.All(w=>w.Box.X>=0&&w.Box.Y>=0&&w.Box.Right<=960&&w.Box.Bottom<=420),"upscaled OCR maps boxes back to original image coordinates");
        Check(Translation.ParseImageContext("[[[0000]]]\n保存\n\n[[[0001]]]\n贴图",2).SequenceEqual(new[]{"保存","贴图"}),"context-aware translation maps back to source regions");
        Check(Translation.ParseImageContext("[0000]\n保存\n\n[0001]\n贴图",2).SequenceEqual(new[]{"保存","贴图"}),"translation accepts normalized marker brackets");
        Check(Translation.DeviceTerms(new[]{"Fold your poker cards."},new[]{"弃牌。"})[0]=="弃牌。","equipment glossary does not alter unrelated meanings");
        bool wrongOrder=false;try{Translation.ParseImageContext("[[[0001]]]\n错位",1);}catch(InvalidOperationException){wrongOrder=true;}Check(wrongOrder,"incorrect translation region markers leave original intact");
        if(Environment.GetEnvironmentVariable("QINGJIE_LIVE_TEST")=="1"){var input=ImageTranslation.Regions(english);var translation=Translation.TranslateImage(input.Select(r=>r.Text).ToArray(),CancellationToken.None).GetAwaiter().GetResult();Console.WriteLine(string.Join(" | ",translation));Check(translation[0].Contains("折叠"),"Fold correctly translated to Chinese with image context via live service");Check(translation.Any(t=>t.Contains("手动")),"adjustable mast heading translated without OCR corruption");ImageFiles.Write(ImageTranslation.Render(darkImage,input,translation),Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"english-live-translation.png"));}
        Console.WriteLine(count+" tests passed.");return 0;
    }catch(Exception e){Console.Error.WriteLine(e);return 1;}}
}
